import { Product } from '../types';

export const LUXURY_PRODUCTS: Product[] = [
  {
    id: 'vp-01',
    name: 'Imperial Zardozi Jamawar Sherwani',
    urduName: 'شاہی زردوزی شیروانی',
    subtitle: 'Woven with pure metallic gold threads & antique dabka work',
    category: 'Couture',
    pricePKR: 485000,
    priceUSD: 1740,
    priceAED: 6390,
    rating: 4.98,
    reviewsCount: 38,
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=1000&q=80',
    badge: 'Masterpiece Guild 2026',
    originCity: 'Lahore',
    artisanHouse: 'Anarkali Heritage Atelier',
    purityCert: 'VELORA Royal Hallmark #LHR-892',
    description: 'Commissioned over 320 hours of master needlecraft. Hand-spun Jamawar silk infused with real gold-plated zari cord and precious stones along the mandarin collar and cuffs.',
    specs: {
      'Fabric': '100% Pure Raw Jamawar Silk',
      'Embroidery': '24K Gold-Dipped Dabka, Naqshi & Zari',
      'Lining': 'Satin Crepe with Hand-Stitched Monogram',
      'Origin': 'Old Anarkali, Lahore',
      'Lead Time': 'Crafted on demand (14 business days)'
    },
    isExclusive: true
  },
  {
    id: 'vp-02',
    name: 'Noor-e-Falak 24K Kundan & Emerald Choker',
    urduName: 'نورِ فلک کندن و زمرد ہار',
    subtitle: 'Heirloom uncut Polki diamonds & natural Swat emerald drops',
    category: 'Jewelry',
    pricePKR: 1250000,
    priceUSD: 4490,
    priceAED: 16490,
    rating: 5.0,
    reviewsCount: 19,
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1000&q=80',
    badge: '24K Gold Certified',
    originCity: 'Swat Valley',
    artisanHouse: 'Swat Gems & Karachi Diamond Quarter',
    purityCert: 'Pak Gemological Institute Cert #PK-9941',
    description: 'An ode to Mughal royal regalia. Features certified untreated deep-green Swat valley emerald briolettes, backed by hand-enameled Meenakari peacocks on pure 24-karat gold.',
    specs: {
      'Gold Purity': '24-Karat Hallmarked Gold (2.8 Tola)',
      'Gemstones': 'Natural Swat Emeralds (42.5 Carats)',
      'Diamonds': 'Uncut Polki Basra setting',
      'Enameling': 'Reverse Meenakari floral motifs',
      'Authentication': 'Micro-engraved VELORA seal with serial'
    },
    isExclusive: true
  },
  {
    id: 'vp-03',
    name: 'Imperial Cordovan Peshawari Chappal',
    urduName: 'شاہی کارڈوون پشاوری چپل',
    subtitle: 'Double-sole Horween shell cordovan with hand-carved tyre tread',
    category: 'Footwear',
    pricePKR: 88000,
    priceUSD: 315,
    priceAED: 1160,
    rating: 4.95,
    reviewsCount: 64,
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=1000&q=80',
    badge: 'Artisan Heritage',
    originCity: 'Peshawar',
    artisanHouse: 'Namak Mandi Master Guild',
    purityCert: 'Full-Grain Certified Leather #PSH-401',
    description: 'The definitive Pakistani luxury footwear. Hand-molded arch support with double-stitched welting, 24K gold-leaf embossed insoles, and solid polished brass hardware.',
    specs: {
      'Leather': 'Glazed Full-Grain Calfskin & Cordovan',
      'Hardware': 'Solid Polished Brass with Anti-Tarnish Coat',
      'Sole': 'Traditional Aeroplane Rubber Recycled Tread',
      'Insole': 'Cushioned memory foam wrapped in Nappa sheepskin',
      'Stitching': 'Waxed linen 9-strand thread'
    }
  },
  {
    id: 'vp-04',
    name: 'Dehn Al Oud Sultani (40-Year Aged)',
    urduName: 'دہن العود سلطانی',
    subtitle: 'Pure wild Cambodi & Assam distillation in crystal gold flacon',
    category: 'Oud',
    pricePKR: 215000,
    priceUSD: 770,
    priceAED: 2830,
    rating: 4.99,
    reviewsCount: 52,
    image: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=1000&q=80',
    badge: 'Private Reserve',
    originCity: 'Islamabad',
    artisanHouse: 'Sultani Perfumers Guild',
    purityCert: '100% Pure Organic Assay #OUD-772',
    description: 'Distilled from wild century-old agarwood trees. Deep balsamic opening with warm honey, royal leather, smoky ambergris, and sweet dried damascena rose. Preserved in hand-cut French lead crystal with 24K gold dipped cap.',
    specs: {
      'Volume': '12ml (1 Tola Pure Concentrated Oil)',
      'Maceration': '40 Years Aged in Sandalwood Casks',
      'Notes': 'Wild Oud, Black Honey, Ambergris, Taif Rose',
      'Bottle': 'Hand-cut 24% Lead Crystal with 24K Gold Dipped Wand',
      'Projection': 'Sillage 36+ hours'
    },
    isExclusive: true
  },
  {
    id: 'vp-05',
    name: 'Crescent Tourbillon Damascus Horology',
    urduName: 'ہلال ٹوربیلون گھڑی',
    subtitle: 'Hand-forged 300-layer Damascus steel case with flying tourbillon',
    category: 'Horology',
    pricePKR: 1850000,
    priceUSD: 6650,
    priceAED: 24400,
    rating: 5.0,
    reviewsCount: 11,
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1000&q=80',
    badge: 'Limited to 14 Pieces',
    originCity: 'Karachi',
    artisanHouse: 'VELORA Haute Horlogerie Atelier',
    purityCert: 'Chronometer Certified C.O.S.C. #CH-014',
    description: 'Pakistani metallurgy married with Swiss micro-engineering. The dial features a meteorite base with 24K gold Pakistani crescent indices and a visible 60-second flying tourbillon carriage.',
    specs: {
      'Movement': 'Calibre VP-902 Manual Wind, 72h Power Reserve',
      'Case': '41mm Wazirabad Hand-Folded Damascus Steel',
      'Dial': 'Gibeon Meteorite & 24K Gold Applied Numerals',
      'Crystal': 'Double Curved Sapphire with Anti-Reflective Coating',
      'Strap': 'Hand-Stitched Matte Black Alligator Leather'
    },
    isExclusive: true
  },
  {
    id: 'vp-06',
    name: 'Kani Pashmina Royal Paisley Shawl',
    urduName: 'شاہی کانی پشمینہ شال',
    subtitle: 'Hand-loomed Himalayan Changthangi cashmere with needlework',
    category: 'Couture',
    pricePKR: 195000,
    priceUSD: 700,
    priceAED: 2570,
    rating: 4.97,
    reviewsCount: 29,
    image: 'https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?auto=format&fit=crop&w=1000&q=80',
    badge: 'Heritage Heirloom',
    originCity: 'Swat Valley',
    artisanHouse: 'Northern Valleys Master Weavers',
    purityCert: '100% Pure Grade A Pashmina Wool',
    description: 'Requires up to 9 months on a traditional wooden loom. The intricate floral jaal pattern is woven using small wooden bobbins (Tujis) containing 36 rich jewel-tone dyes.',
    specs: {
      'Dimension': '100 x 200 cm (Royal Stole)',
      'Fineness': '12-14 Micron Grade A Underbelly Fleece',
      'Technique': 'Authentic Kani Bobbin Weave',
      'Weight': 'Surreally light 220 grams',
      'Packaging': 'Carved Walnut Wood Velvet-Lined Casket'
    }
  },
  {
    id: 'vp-07',
    name: 'Multani Azure Camel-Hide Diplomat Briefcase',
    urduName: 'ملتانی کیمل ہائیڈ بریف کیس',
    subtitle: 'Hand-painted Kashigari motif on vegetable-tanned full-grain hide',
    category: 'Accessories',
    pricePKR: 135000,
    priceUSD: 485,
    priceAED: 1780,
    rating: 4.92,
    reviewsCount: 23,
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=1000&q=80',
    badge: 'Artisan Pride',
    originCity: 'Multan',
    artisanHouse: 'Multan Naqashi & Leather Collective',
    purityCert: 'UNESCO Master Craft Honor #MLT-118',
    description: 'Each hide is cured over 45 days in natural acacia barks, then painted by 4th-generation Multani artisans using blue cobalt mineral pigments and 24K gold leaf outlining.',
    specs: {
      'Material': 'Desert Camel Hide (Vegetable Tanned)',
      'Hardware': 'Solid Gold-PVD Coated Dual Combination Lock',
      'Interior': 'Suede leather with padded 16” laptop chamber',
      'Dimensions': '42cm x 30cm x 9cm',
      'Guarantee': '50-Year Structural Guild Warranty'
    }
  },
  {
    id: 'vp-08',
    name: 'Jahanara 24K Polki Jhumkas with Basra Pearls',
    urduName: 'جہاں آرا پولکی جھمکے',
    subtitle: 'Cascading natural Basra seed pearls & untreated Burmese rubies',
    category: 'Jewelry',
    pricePKR: 640000,
    priceUSD: 2300,
    priceAED: 8440,
    rating: 4.98,
    reviewsCount: 41,
    image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1000&q=80',
    badge: 'Heirloom Certified',
    originCity: 'Lahore',
    artisanHouse: 'Old City Gold Souk Guild',
    purityCert: 'Lahore Assay Office 24K Stamp',
    description: 'Inspired by the Empress Jahanara. Hand-hammered 24K gold domes suspended with graduated natural Basra pearl drops and pigeon-blood ruby cabochons.',
    specs: {
      'Gold': '24K Gold Hallmarked (1.4 Tola)',
      'Pearls': 'Certified Natural Basra Saltwater Pearls',
      'Rubies': 'Unheated Natural Burmese (3.2 Carats)',
      'Closure': 'Traditional screw-back with safety chain'
    }
  },
  {
    id: 'vp-09',
    name: 'Zari Khussa with Seed Pearls & Velvet',
    urduName: 'مخمل زری کھسہ',
    subtitle: 'Deep obsidian Italian velvet embroidered with pure silver tilla',
    category: 'Footwear',
    pricePKR: 42000,
    priceUSD: 150,
    priceAED: 550,
    rating: 4.90,
    reviewsCount: 77,
    image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=1000&q=80',
    badge: 'Handmade Luxury',
    originCity: 'Peshawar',
    artisanHouse: 'Peshawar Royal Cobblers',
    purityCert: 'Craft Heritage Standard #KH-59',
    description: 'Ergonomically curved traditional toe (Nok) lined with glove-soft lambskin to prevent bites. Adorned with delicate micro-pearls and hand-twisted metallic tilla.',
    specs: {
      'Upper': 'Pure Silk Velvet in Obsidian Black',
      'Lining': 'Butter-Soft Italian Nappa Leather',
      'Sole': 'Single-Piece Vegetable Tanned Cowhide',
      'Embroidery': 'Silver Tilla & Fresh Seed Pearls'
    }
  }
];

export const CITIES = ['All', 'Lahore', 'Karachi', 'Peshawar', 'Multan', 'Swat Valley', 'Islamabad'] as const;
